#!/bin/sh
# Update Fluxbox menu:

echo "Updating fluxbox menu: update-desktop-database"
for x in `ps -C fluxbox -o user=`; do su --login $x -c "xdg_menu --format fluxbox --root-menu /etc/xdg/menus/arch-applications.menu >~/.fluxbox/my-menu"
update-desktop-database

