#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.
# Change your keymap:
# xmodmap "$HOME/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN & AT THE END.

#(sleep 3 && /usr/bin/nm-applet --sm-disable) 
fbsetbg -l &
conky -q &
(sleep 5 && volumeicon) &
#compton --config ~/.config/compton/compton.conf &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with exec before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "$fluxdir/log"